logging.level.jp.co.kpscorp=debug
#logging.level.org.springframework=debug
#本番↓
#テスト↓
spring.datasource.url=jdbc:postgresql://localhost:5432/rc6
spring.datasource.username=genext
spring.datasource.password=ge201700
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.tomcat.max-active=5
spring.datasource.tomcat.max-idle=3
spring.datasource.tomcat.min-idle=0
spring.datasource.tomcat.initial-size=0
spring.datasource.tomcat.remove-abandoned=true
#uploadはApache FileUploadで処理
spring.servlet.multipart.enabled=false
#key secret
#rc6.consumerKey.localhost=3MVG9yZ.WNe6byQAQYDKqo6PLjc591mMz3IAmk.aWDja2Se8pSccj3pPE1ia.xkU1BaUYMjj_CRjevXAxbOQQ
#rc6.consumerSeacret.localhost=4074250845829334396
#使用するserver名に対して oauthの設定を行う
rc6.consumerKey.media.swtaira.com=3MVG9dAEux2v1sLvPiFAFtEq2smrcatOfzJCXLM83_YilCy7_.mh2htjYtxsGfzFtQH.LNJ2_bsSELCakCvUE
rc6.consumerSeacret.media.swtaira.com=AA15900AA1EC89B4784875CF8CB4E4A26D78D4E7FBC6E4E0D0D450468FD9AD59
rc6.canvasSeacret.media.swtaira.com=6097363852950086932

# req.getRequestURL()でproxyの元のURLを返すようにする設定
server.forward-headers-strategy=framework
# 開発環境のトンネル設定で コンテキストパスを取ってしまっているため必要 ProxyPass /rc6/ http://localhost:3000/
#server.servlet.context-path=/rc6

# spring.thymeleaf.prefix=classpath:/templates/
# spring.thymeleaf.suffix=.html
