logging.level.jp.co.kpscorp=debug
#logging.level.org.springframework=debug
#本番↓
#テスト↓
spring.datasource.url=jdbc:postgresql://localhost:5432/rc6
spring.datasource.username=genext
spring.datasource.password=ge201700
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.tomcat.max-active=5
spring.datasource.tomcat.max-idle=3
spring.datasource.tomcat.min-idle=0
spring.datasource.tomcat.initial-size=0
spring.datasource.tomcat.remove-abandoned=true
