# 開発時にこのpropertiesを使用するにはlaunch.jsonの設定で "vmArgs": "-Dspring.profiles.active=dev"を設定する
#spring.thymeleaf.cache=false
logging.level.org.hibernate.SQL=debug
spring.jpa.show-sql=true
#templateのソースの修正が即時に反映されるようにするにはソースのパスをfile:でアクセスするようにする
#この設定はMyThymeleafConfigで使用される
dev.template.path=file:src/main/resources/templates/
#scon2.template.path=file:zscon2resorces/templates/
 # 開発時にdeploy時と同様になるようにコンテキストパスを設定する
server.servlet.context-path=/rc6
