logging.level.jp.co.kpscorp=debug
#logging.level.org.springframework=debug
#本番↓
#テスト↓
spring.datasource.url=jdbc:postgresql://localhost:5432/rc6
spring.datasource.username=genext
spring.datasource.password=ge201700
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.tomcat.max-active=5
spring.datasource.tomcat.max-idle=3
spring.datasource.tomcat.min-idle=0
spring.datasource.tomcat.initial-size=0
spring.datasource.tomcat.remove-abandoned=true
#uploadはApache FileUploadで処理
spring.servlet.multipart.enabled=false
#key secret
rc6.consumerKey.localhost=3MVG9yZ.WNe6byQAQYDKqo6PLjc591mMz3IAmk.aWDja2Se8pSccj3pPE1ia.xkU1BaUYMjj_CRjevXAxbOQQ
rc6.consumerSeacret.localhost=4074250845829334396
rc6.canvasSeacret.localhost=6097363852950086932