net.sf.jasperreports.awt.ignore.missing.font=true
net.sf.jasperreports.default.pdf.encoding=Cp1252
net.sf.jasperreports.default.pdf.font.name=Times-Roman
net.sf.jasperreports.default.pdf.embedded=false